import { v4 as uuidv4 } from "uuid";
import YAML from "yaml";
import { generateWithFallback } from "@/lib/ollama-client";
import { sanitizePromptInput } from "@/lib/security/sanitize";

export interface SigmaInput {
  title: string;
  description?: string;
  alert?: Record<string, unknown>;
  mitre_techniques?: string[];
  suspicious_strings?: string[];
  verdict?: string;
}

export interface SigmaRule {
  rule_name: string;
  rule_title: string;
  rule_yaml: string;
  rule_level: "informational" | "low" | "medium" | "high" | "critical";
  mitre_techniques: string[];
}

function toRuleLevel(verdict?: string): SigmaRule["rule_level"] {
  switch ((verdict || "").toLowerCase()) {
    case "clean":
      return "informational";
    case "suspicious":
      return "medium";
    case "malicious":
      return "high";
    default:
      return "medium";
  }
}

function slugifyRuleName(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 120);
}

function normalizeTechniques(techniques?: string[]): string[] {
  return (techniques || [])
    .map((item) => item.trim())
    .filter(Boolean)
    .slice(0, 20);
}

function extractYaml(text: string): string {
  const fenced = text.match(/```yaml\s*([\s\S]*?)```/i);
  if (fenced?.[1]) {
    return fenced[1].trim();
  }

  const genericFenced = text.match(/```\s*([\s\S]*?)```/);
  if (genericFenced?.[1]) {
    return genericFenced[1].trim();
  }

  return text.trim();
}

function validateSigmaYaml(ruleYaml: string): {
  valid: boolean;
  parsed?: any;
  error?: string;
} {
  try {
    const parsed = YAML.parse(ruleYaml);
    const requiredFields = [
      "title",
      "id",
      "status",
      "description",
      "logsource",
      "detection",
      "falsepositives",
      "level",
    ];

    for (const field of requiredFields) {
      if (!(field in parsed)) {
        return { valid: false, error: `Missing Sigma field: ${field}` };
      }
    }

    if (
      parsed?.logsource?.product !== "wazuh" ||
      parsed?.logsource?.service !== "alerts"
    ) {
      return {
        valid: false,
        error: "Sigma logsource must target wazuh alerts",
      };
    }

    return { valid: true, parsed };
  } catch (error) {
    return {
      valid: false,
      error: error instanceof Error ? error.message : "Invalid YAML",
    };
  }
}

export function generateSigmaRule(input: SigmaInput): string {
  const now = new Date();
  const date = `${now.getUTCFullYear()}-${String(now.getUTCMonth() + 1).padStart(2, "0")}-${String(now.getUTCDate()).padStart(2, "0")}`;
  const techniques = normalizeTechniques(input.mitre_techniques);
  const detectionValues = (input.suspicious_strings || [])
    .map((item) => item.trim())
    .filter(Boolean)
    .slice(0, 8);

  const sigmaRule = {
    title: input.title,
    id: uuidv4(),
    status: "experimental",
    description:
      input.description ||
      "Generated by Phish-Slayer detection engineering pipeline",
    author: "Phish-Slayer",
    date,
    logsource: {
      product: "wazuh",
      service: "alerts",
    },
    detection: {
      selection:
        detectionValues.length > 0
          ? {
              "message|contains": detectionValues,
            }
          : {
              "rule.description|contains": [input.title],
            },
      condition: "selection",
    },
    falsepositives: [
      "Legitimate administrative operations",
      "Security tooling test activity",
    ],
    level: toRuleLevel(input.verdict),
    tags: techniques.map((technique) => `attack.${technique.toLowerCase()}`),
  };

  return YAML.stringify(sigmaRule);
}

export async function generateWithGemini(
  alert: Record<string, unknown>,
  analysisData?: Record<string, unknown>,
): Promise<SigmaRule> {
  const alertTitle =
    typeof alert.rule_description === "string"
      ? alert.rule_description
      : "Phish-Slayer generated detection";
  const mitreTechniques = normalizeTechniques(
    Array.isArray(analysisData?.mitre_techniques)
      ? (analysisData?.mitre_techniques as string[])
      : Array.isArray(alert.mitre_technique_id)
        ? (alert.mitre_technique_id as string[])
        : [],
  );

  const fallbackYaml = generateSigmaRule({
    title: alertTitle,
    description:
      typeof alert.rule_description === "string"
        ? alert.rule_description
        : undefined,
    alert,
    mitre_techniques: mitreTechniques,
    suspicious_strings: Array.isArray(analysisData?.suspicious_strings)
      ? (analysisData?.suspicious_strings as string[])
      : [],
    verdict:
      typeof analysisData?.verdict === "string"
        ? analysisData.verdict
        : "suspicious",
  });

  const safeAlert = sanitizePromptInput(JSON.stringify(alert, null, 2), 3000);
  const safeAnalysis = sanitizePromptInput(
    JSON.stringify(analysisData || {}, null, 2),
    3000,
  );

  const prompt = `Generate a valid Sigma rule YAML for this security alert. Return ONLY YAML.\n\nRequirements:\n- Include title, id, status, description, author, date, logsource, detection, falsepositives, level, tags\n- logsource.product must be \"wazuh\"\n- logsource.service must be \"alerts\"\n- Keep rule practical and concise\n\nAlert:\n${safeAlert}\n\nStatic analysis (optional):\n${safeAnalysis}`;

  try {
    const rawText = await generateWithFallback(prompt, prompt);

    if (!rawText) {
      throw new Error("Model returned empty response");
    }

    const extractedYaml = extractYaml(rawText);
    const validation = validateSigmaYaml(extractedYaml);
    if (!validation.valid || !validation.parsed) {
      throw new Error(validation.error || "Sigma YAML validation failed");
    }

    const parsed = validation.parsed;
    const detectedLevel = [
      "informational",
      "low",
      "medium",
      "high",
      "critical",
    ].includes(parsed.level)
      ? (parsed.level as SigmaRule["rule_level"])
      : "medium";

    const tags = Array.isArray(parsed.tags) ? parsed.tags : [];
    const parsedTechniques = tags
      .filter((tag: unknown): tag is string => typeof tag === "string")
      .filter((tag: string) => tag.startsWith("attack."))
      .map((tag: string) => tag.replace(/^attack\./, ""));

    return {
      rule_name: slugifyRuleName(
        typeof parsed.title === "string" ? parsed.title : alertTitle,
      ),
      rule_title: typeof parsed.title === "string" ? parsed.title : alertTitle,
      rule_yaml: extractedYaml,
      rule_level: detectedLevel,
      mitre_techniques:
        parsedTechniques.length > 0 ? parsedTechniques : mitreTechniques,
    };
  } catch (error) {
    console.error(
      "[sigma-generator] Falling back to deterministic Sigma rule",
      error,
    );

    return {
      rule_name: slugifyRuleName(alertTitle),
      rule_title: alertTitle,
      rule_yaml: fallbackYaml,
      rule_level: toRuleLevel(
        typeof analysisData?.verdict === "string"
          ? analysisData.verdict
          : "suspicious",
      ),
      mitre_techniques: mitreTechniques,
    };
  }
}
